feature(13)/init front
knowdateapp/knowdateapp pull request #15
Opened 2024-03-11 06:42 UTC by BuffiBuchi

#13

2024-03-11 22:06 UTC, meetmorrowsolonmars requested changes

2024-03-12 05:44 UTC, BuffiBuchi commented on .gitignore
> +*.sw?
Катя вс код использует.  Поэтому я оставил сгенеренный файл так хз  какие файлы там

2024-03-12 12:47 UTC, meetmorrowsolonmars commented on .gitignore
> +*.sw?
Ну вот .sln файлы точно ни кто не использует, это файл "решения" из visual studio. Я бы почистил.

2024-03-13 08:03 UTC, BuffiBuchi commented on frontend/.eslintrc.cjs
> +  ignorePatterns: ["dist", ".eslintrc.cjs", "index.html"],
Да,но не совсем, там будет уже итоговый js файл не только транспилированный, но и потимизированный. Так же там уже будет html файли и необходимые медиа файлы

2024-03-13 08:07 UTC, BuffiBuchi commented on frontend/.eslintrc.cjs
> +  ignorePatterns: ["dist", ".eslintrc.cjs", "index.html"],
html файл индекса нет смысла проверять, как и сам файл конфига и файл билда. Файлы билда будут не соотвествовать правилам линтера так как они будут минимизированы. 

Eslint это инструмент статического анализа кода скорее что бы ошибки посдвечивать, а не поддерживать стиль кода. Для поддержания стиля кода используется prettier и все файлы им форматируются. Конфиг eslint-а я также форматировал prettier. В eslint отключены правила которые конфликтуют с prettier.

Впринципе можем обусдить стайл код и я включу правила в prettier и отформатирую весь проект. Я бы вынес это в отдельную задачу тогда

2024-03-13 08:09 UTC, BuffiBuchi commented on frontend/README.md
> +- Replace `plugin:@typescript-eslint/recommended` to `plugin:@typescript-eslint/recommended-type-checked` or `plugin:@typescript-eslint/strict-type-checked`
Он уже стоит более строгий, не смотрел конфиг eslint? Я не стал ставить самый строгий, так как его советуют при высокм уровне знания ts использовать. Я не стал его ставить так как вижу подводные камни с типизицией библиотек которые использую. Можно поставить самый строгий конфиг, но я считаю и этого хватит. 
<img width="496" alt="image" src="https://github.com/knowdateapp/knowdateapp/assets/41388910/deb807f4-d6b8-4376-aa4f-e1f520f20c22">

2024-03-13 08:11 UTC, BuffiBuchi commented on frontend/package.json
> +  "scripts": {
Давай сделаю это в рамках таски с README. В рамкха README я буду еще дополнять package.json

2024-03-13 08:15 UTC, BuffiBuchi commented on frontend/src/app/providers/emotion-theme-provider.tsx
> +  children: ReactElement;
Это провайдер для передачи контекста в приложение. В данном случае мы передаем контекст emotion который содежит тему приложения и утулиты разные. Интерфейс описывает пропсы компонента. У провайдера есть только один компонент это потом его.

`<EmotionProvider><App/> </EmotionProvider>`
App является children. Так как мы обернули App в провайдер мы можем ниже по деревеу компонентов( в App и всех компонентах которые содержаит App и так далее) использовать хук useTheme(), который нам вернет тему приложения. Во все остальные провайдеры мы также оборочиваем что бы получить доступ к различным контекстам.

2024-03-13 08:20 UTC, BuffiBuchi commented on frontend/src/pages/collection/index.ts
> +export { CollectionPage } from './ui/collection-page.tsx';
tsx файл содержит jsx, ts нет. JSX это расширение js-a позволяющее нам создавать вестку в js файлах. Компонент отличается от простой функции  или хука js так как он как раз возращает в результате своей работы разметку в формате jsx. Не понял, в примере и в строке же есть расширения файла. У обоих файлов расширение .tsx, не?

2024-03-13 08:23 UTC, BuffiBuchi commented on frontend/src/shared/api/query-client.ts
> +      staleTime: -Infinity,
Это клиент для бибилиотеки react-query. Через него настраиваются различные опции хуков которые я буду использовать для работы с апи. В след задаче настрою еще apiService который будет делать уже сами запросы к беку.

2024-03-13 08:33 UTC, BuffiBuchi commented on frontend/src/vite-env.d.ts
> +/// <reference types="vite/client" />
Строка нужна, это директива ts-а ///. Это не коммент вообщем.

2024-03-13 08:38 UTC, BuffiBuchi commented on frontend/tsconfig.json
> +    "allowSyntheticDefaultImports": true
<img width="271" alt="image" src="https://github.com/knowdateapp/knowdateapp/assets/41388910/817d5bb3-84f4-4a3c-9078-43ccf08ee1b4">

2024-03-13 08:45 UTC, BuffiBuchi commented on frontend/vite.config.ts
> +// https://vitejs.dev/config/
да, ссылка на документацию

2024-03-13 09:26 UTC, BuffiBuchi commented on .gitignore
> +*.sw?
УДалил .sln

2024-03-13 21:33 UTC, meetmorrowsolonmars commented on frontend/.eslintrc.cjs
> +  ignorePatterns: ["dist", ".eslintrc.cjs", "index.html"],
Не, я про форматирование JSON файлов. Просто в WebStorm встроен функционал форматирования файлов, он форматирует JSON файлы по другому. Я бы использовал его или какой-то форматер. Чтоб все в едином стиле было, но это душнилово. Можно не делать.

2024-03-13 21:35 UTC, meetmorrowsolonmars commented on frontend/README.md
> +- Replace `plugin:@typescript-eslint/recommended` to `plugin:@typescript-eslint/recommended-type-checked` or `plugin:@typescript-eslint/strict-type-checked`
Я вот сейчас смотрел extends и там другой линтер указан.

<img width="567" alt="image" src="https://github.com/knowdateapp/knowdateapp/assets/24230649/480c7861-b19f-41f5-98c2-a7e31510930b">

2024-03-13 21:37 UTC, meetmorrowsolonmars commented on frontend/src/shared/api/query-client.ts
> +      staleTime: -Infinity,
Почему тут -Infinity?

2024-03-13 21:38 UTC, meetmorrowsolonmars commented on frontend/vite.config.ts
> +// https://vitejs.dev/config/
А ты хоть раз им пользовался?

2024-03-13 21:38 UTC, meetmorrowsolonmars commented on frontend/vite.config.ts
> +// https://vitejs.dev/config/
А ты хоть раз им пользовался?

2024-03-13 21:40 UTC, meetmorrowsolonmars commented on frontend/src/pages/collection/index.ts
> +export { CollectionPage } from './ui/collection-page.tsx';
Ну ты внутри файла посмотри. Там не указывается расширение в импортах. Но я так понимаю, что можно не указывать только расширения .ts в импорте, а .tsx нужно указывать. Верно?

2024-03-14 11:34 UTC, BuffiBuchi commented on frontend/README.md
> +- Replace `plugin:@typescript-eslint/recommended` to `plugin:@typescript-eslint/recommended-type-checked` or `plugin:@typescript-eslint/strict-type-checked`
My bad. Исправил

2024-03-14 11:35 UTC, BuffiBuchi commented on frontend/src/pages/collection/index.ts
> +export { CollectionPage } from './ui/collection-page.tsx';
Нет. Если в директории есть файл index.ts/tsx то импорт происходит по умолчанию из него. Там расширение не указано потому что там указана директория в которой находится index.ts

2024-03-14 11:37 UTC, BuffiBuchi commented on frontend/vite.config.ts
> +// https://vitejs.dev/config/
Да когда добавлял плагины))) Думаешь удалить?

2024-03-14 11:46 UTC, BuffiBuchi commented on frontend/src/vite-env.d.ts
> +/* eslint-disable @typescript-eslint/no-empty-interface */
Отключил правило на eslint запрещающее пустые интерфейсы. В этом файле передопределяются или расширяются интрефейсы библиотек. В данном случае я расширяю интрефейс темы из emotion интерфейсом темы antd. Так как я использую тему antd мне нечего добавить в интерейс и я просто расширяю его интерфейсом GlobalToken

2024-03-14 16:59 UTC, sevrkk approved these changes

2024-03-14 19:04 UTC, meetmorrowsolonmars approved these changes

2024-03-14 19:06 UTC, merged