GRPC сервер для User
knowdateapp/knowdateapp pull request #16
Opened 2024-03-11 16:14 UTC by sevrkk

2024-03-11 22:22 UTC, meetmorrowsolonmars requested changes

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +		lis, err := net.Listen("tcp", ServerAddressGRPC)
Вот тут мы говорим, что хотим слушать такой-то порт и адрес по протоколу TCP. Если это сделать не получилось, то мы не можем запустить приложение, поэтому тут `log.Fatalln` допустим. Я бы предложил только вынести это в main, а не в отдельную горутину. Эта операция не блокирующая и мы результат ее выполнения можем сразу узнать.

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +		err = server.Serve(lis)
Вот тут мы начинаем обрабатывать входящие подключения к GRPC серверу. Я согласен с тем, что это можно запустить в отдельной горутине и в main реализовать graceful shutdown.

Но я предлагаю проверить документацию `server.GracefulStop` и `server.Serve` функций. Если мне не изменяет память, то при вызове GracefulStop функции Serve сразу возвращает нам ошибку и завершает выполнение. При этом обработка уже принятых запросов продолжается. Ошибка в этом случае говорит нам о том, что новые подключения перестали обрабатываться. Надо перепроверить.

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +	server.GracefulStop()
Тут все кайф сделано, ожидаем получение сигнала о завершении приложения.

Я бы только попробовал учесть ситуацию, при которой работа `server.Serve` действительно завершается ошибкой и приложение перестает выполнять свою главную функцию "обработку входящих соединений/запросов". В этом случае нам нет необходимости дожидаться входящего сигнала о завершении процесса и мы можем сами прервать его выполнение логируя ошибку. Иначе просто процесс продолжит ждать сигнал, но при этом ничего уже делать не будет.

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/internal/app/v1/auth/login_anonymous_user.go
> +	desc "github.com/knowdateapp/knowdateapp/backend/user/internal/pb/api/v1/auth"
Я предлагаю разделять импорты на 3 категории.

1. Стандартная библиотеки.
2. Сторонние библиотеки.
3. Собственные импорты.

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/internal/app/v1/auth/login_anonymous_user.go
> +var signingKey = []byte("test")
Мы проверяли как работает подпись с этой строкой? Мне кажется, что там под капотом должна быть проверка на формат ключа и мы тут будем падать при выполнении.

2024-03-11 22:22 UTC, meetmorrowsolonmars commented on backend/user/internal/app/v1/auth/login_anonymous_user.go
> +		return nil, status.Error(codes.Internal, "token generation error")
Тут у нас исключительная ситуация, которая должна редко появляться. Поэтому ошибку тут стоит написать в лог с уровнем Error. В тело ответа ее добавлять не стоит, потому что это может раскрыть уязвимость нашего приложения, но в логи записать можно для дебага. Это нам поможет в будущем.

2024-03-14 12:43 UTC, sevrkk commented on backend/user/internal/app/v1/auth/login_anonymous_user.go
> +var signingKey = []byte("test")
проверила, работает. для hmac ключ в таком формате нужен

2024-03-14 13:12 UTC, sevrkk commented on backend/user/cmd/app/main.go
> +		err = server.Serve(lis)
в serve вот такое написано: // Stop or GracefulStop called; block until done and return nil.

2024-03-20 16:23 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +		err = server.Serve(lis)
**Stop**

> **Stop** stops the gRPC server. It immediately closes all open connections and listeners. It cancels all active RPCs on the server side and the corresponding pending RPCs on the client side will get notified by connection errors.

GracefulStop

> **GracefulStop** stops the gRPC server gracefully. It stops the server from accepting new connections and RPCs and blocks until all the pending RPCs are finished.

2024-03-20 16:26 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +		err = server.Serve(lis)
Понял, ты права. Тут можно ошибку обрабатывать так же.

2024-03-20 16:33 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +	server.GracefulStop()
Реализация рабочая и по сути проблем с ней не будет я думаю ни когда. Но потенциально они возможны, потому что мы закрываем канал, которую передали в функцию Notify. Значит когда функция будет писать в канал будет паника.

Это просто выглядит не сильно хорошо с точки зрения кода. Что мы допускаем это. Я бы заменил на NotifyContext и его бы отменял вместо закрытия канала. Это безопасно.

2024-03-20 16:34 UTC, meetmorrowsolonmars commented on backend/user/internal/app/v1/auth/login_anonymous_user.go
> +var signingKey = []byte("test")
Ок пока оставим так, потом из конфига брать будем

2024-03-26 09:29 UTC, meetmorrowsolonmars commented on backend/user/cmd/app/main.go
> +	server.GracefulStop()
Супер

2024-03-26 09:29 UTC, merged