Добавлена фича создания карточек
knowdateapp/knowdateapp pull request #30
Opened 2024-07-24 21:11 UTC by meetmorrowsolonmars

2024-07-25 08:14 UTC, BuffiBuchi requested changes

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/entities/session/model/context.ts
> +export type AuthContextType = {
И так понятно что это тип, мы же не пишем NoteComponent?

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +} from 'features/auth/model';
Тут можно обсудить какие импорты предпочтительные. В рамках модуля обсолютные юзаем или относительные. Или обсолютные только когда идем по древу файлов вниз

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +      <Heading>{t('features.auth.auth-form.title')}</Heading>
пишем на js, переводы хранятся в JSON-е, значит используем camelCase

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/create-card/api/use-create-card.ts
> +  return useMutation<AxiosResponse<CardEntity>, IApiError, CreateCardParams>({
Вот тут по сути useMutation берет <AxiosResponse<CardEntity>, IApiError, CreateCardParams> всю эту портянку типов из cardsController.createCard. Меньше кода - легче жить.

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/create-card/ui/create-card-form-modal/create-card-form-modal.tsx
> +  const { register, handleSubmit, reset } = useForm<CreateCardFormData>();
Забыл написать
`// TODO добавить валидацию формы`

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/create-note/ui/create-note-button/create-note-button.tsx
> +import { useCreateNote } from 'features/create-note/api';
должно быть `import { useCreateNote } from 'features/create-note';`

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +  const { t } = useTranslation('translation');
у нас один неймспейс и тот с дефолтным названием. Его можно не указывать

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +          padding="0.5em 0"
зачем em? 0.5 em это сколько?

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/pages/cards/ui/cards-page.tsx
> +    <Box>
зачем `Box`?

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/shared/model/schema.ts
> +export type Workspace = string;
удали тип тогда совсем, зачем он нам нужен если это просто string причем любая

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/widgets/header/ui/header.tsx
> +          <CreateCardFormModal />
обманчивое название компонента, вроде модалка, а появится и модалка и кнопка

2024-07-25 08:14 UTC, BuffiBuchi commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +    // TODO: Нужно более гибким способом задавать количество элементов в строке.
Раз уеж мы комменты и TODO пишем на русском, может тогда и сообщения к коммитам тоже на русском?

2024-07-25 20:13 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/types/card-entity.ts
> +export type CardEntity = {
Не понимаю что делать с компонентом Note. С интерфейсом конфликтов не было, а с типом есть.

2024-07-25 20:13 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/types/card-entity.ts
> +export type CardEntity = {
Ты говорил про какую-то настройку

2024-07-25 20:13 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/types/card-entity.ts
> +export type CardEntity = {
может надо ее потыкать

2024-07-25 20:13 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/types/card-entity.ts
> +  workspace: string;
должен

2024-07-25 20:14 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +    // TODO: Нужно более гибким способом задавать количество элементов в строке.
Мне с точки зрения css свойств не понятно как это сделать. Например, как отключить скрол горизонтальный. А не как разбить на компоненты.

2024-07-25 20:14 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +    // TODO: Нужно более гибким способом задавать количество элементов в строке.
List общий пока делать не буду. Хочу делать фичи

2024-07-25 20:14 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +          <Card key={card.id} card={card} />
Почему?

2024-07-25 20:15 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card/card.tsx
> +export const Card: FC<Props> = ({ card }) => {
норм тема

2024-07-25 20:15 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card/card.tsx
> +    // TODO: Задать константный размер карточки и обрезать вопрос при помощи троеточия.
Ага, но в этом МР не буду делать.

2024-07-25 20:16 UTC, meetmorrowsolonmars commented on frontend/src/entities/session/model/context.ts
> +export type AuthContextType = {
Проблема как и с NoteEntity. Конфликт имен) Если знаешь как решить предлагай

2024-07-25 20:16 UTC, meetmorrowsolonmars commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +} from 'features/auth/model';
Хм, не знаю. Мне без разницы)

2024-07-25 20:16 UTC, meetmorrowsolonmars commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +} from 'features/auth/model';
Как правильно?

2024-07-25 20:17 UTC, meetmorrowsolonmars commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +      <Heading>{t('features.auth.auth-form.title')}</Heading>
ок

2024-07-25 20:18 UTC, meetmorrowsolonmars commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +          padding="0.5em 0"
Не ебу) Я хотел отступ внутри кнопки, чтоб меню было пошире) Расскажи как сделать лучше

2024-07-25 20:18 UTC, meetmorrowsolonmars commented on frontend/src/pages/cards/ui/cards-page.tsx
> +    <Box>
У тебя взял) Тоже не знаю) Ты так сделал в notes-page

2024-07-25 20:21 UTC, meetmorrowsolonmars commented on frontend/src/shared/model/schema.ts
> +export type Workspace = string;
В таких кейсах тип может быть полезен, если ты не хочешь путать аргументы. Условно у тебя PostingID, ClearingID и CommonID. И если ты не хочешь их перепутать при присваивании это нормальная практика создавать для них тип.

Тут зависит от того как мы будем определять отсутствие Workspace. Для этого подходит null, но тогда нужно его везде использовать. Но на бэке null не может передаваться, поэтому в моделях его нужно запретить или явно проверять. Так что тут нужно обсудить как лучше.

2024-07-25 20:22 UTC, meetmorrowsolonmars commented on frontend/src/widgets/header/ui/header.tsx
> +          <CreateCardFormModal />
Так делают в большинстве примеров кода. Отдельно кнопку просто без функционала модалки я пока не вижу)

2024-07-25 20:22 UTC, meetmorrowsolonmars commented on frontend/src/widgets/header/ui/header.tsx
> +          <CreateCardFormModal />
Если так плохо делать, то я бы хотел чтоб ты рассказал как лучше

2024-07-25 20:22 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +    // TODO: Нужно более гибким способом задавать количество элементов в строке.
Нет)

2024-07-25 20:23 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +    // TODO: Нужно более гибким способом задавать количество элементов в строке.
Если тебя это смущает, то я буду писать на английском все. Но комментарии будут удаляться и исправляться, а история коммитов с нами на всегда

2024-07-25 20:25 UTC, meetmorrowsolonmars commented on frontend/src/shared/model/schema.ts
> +export type Workspace = string;
Тут можно сделать null, но тогда перед отправкой запроса нужна валидация на not null.

2024-07-25 20:25 UTC, meetmorrowsolonmars commented on frontend/src/shared/model/schema.ts
> +export type Workspace = string;
И вообще может много где это нужно сделать?

2024-07-25 20:40 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card/card.tsx
> +export const Card: FC<Props> = ({ card }) => {
Давай отдельно будем делать. Не хочу переделывать все. По ходу работы с кодом будем делать это

2024-07-25 20:41 UTC, meetmorrowsolonmars commented on frontend/src/entities/note/types/note-entity.ts
> +  content_uri: string;
Можно преобразовывать в контролере. Нет?

2024-07-25 20:44 UTC, meetmorrowsolonmars commented on frontend/src/features/create-card/api/use-create-card.ts
> +  return useMutation<AxiosResponse<CardEntity>, IApiError, CreateCardParams>({
IApiError он не может распарсить) Потому что в controller про него ни слова

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +  const { t } = useTranslation('translation');
Готово.

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/features/create-note/ui/create-note-button/create-note-button.tsx
> +import { useCreateNote } from 'features/create-note/api';
Готово.

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/features/create-card/ui/create-card-form-modal/create-card-form-modal.tsx
> +  const { register, handleSubmit, reset } = useForm<CreateCardFormData>();
Готово.

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/features/auth/ui/auth-form/auth-form.tsx
> +      <Heading>{t('features.auth.auth-form.title')}</Heading>
Готово

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/ui/card-list/card-list.tsx
> +          <Card key={card.id} card={card} />
Убрал, но расскажи почему.

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/entities/card/types/card-entity.ts
> +  workspace: string;
Готово

2024-07-25 20:47 UTC, meetmorrowsolonmars commented on frontend/src/app/app.tsx
> +  const [workspace, setWorkspace] = useState<Workspace>(localStorage.getItem('workspace') || '');
Готово

2024-07-29 15:59 UTC, meetmorrowsolonmars commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +          padding="0.5em 0"
делаем в пиксилях

2024-07-29 16:00 UTC, meetmorrowsolonmars commented on frontend/src/features/hamburger-menu/ui/hamburger-menu-button/hamburger-menu-button.tsx
> +          padding="0.5em 0"
просо цифры передаем

2024-07-29 16:08 UTC, BuffiBuchi commented on frontend/src/widgets/header/ui/header.tsx
> +          <CreateCardFormModal />
Можно добавить постфикс Button

2024-07-29 16:09 UTC, meetmorrowsolonmars commented on frontend/src/pages/cards/ui/cards-page.tsx
> +    <Box>
удаляем

2024-08-08 19:09 UTC, merged